on:
  push:
    branches:
      - master
      - "greenkeeper/*"
  pull_request:
    types: [opened, synchronize]
name: Test
jobs:
  readmeExample:
    name: "[TEST] README example"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: "npm ci"
      - run: "npm run build"
      - id: action_with_json_output
        run: 'node -p "require(''@actions/core'').setOutput(''data'', JSON.stringify({foo: {bar: ''baz''}}))"'
      - id: data
        uses: ./
        with:
          json: ${{ steps.action_with_json_output.outputs.data }}
          bar: "foo.bar"
      - run: 'node -e "assert.equal(''baz'', ''${{ steps.data.outputs.bar }}'')"'
